
export const timezones = [
  { value: 'UTC', label: 'UTC' },
  { value: 'Africa/Abidjan', label: '(GMT+0:00) Abidjan' },
  { value: 'Africa/Accra', label: '(GMT+0:00) Accra' },
  { value: 'Africa/Algiers', label: '(GMT+1:00) Algiers' },
  { value: 'Africa/Cairo', label: '(GMT+2:00) Cairo' },
  { value: 'Africa/Casablanca', label: '(GMT+1:00) Casablanca' },
  { value: 'Africa/Johannesburg', label: '(GMT+2:00) Johannesburg' },
  { value: 'Africa/Lagos', label: '(GMT+1:00) Lagos' },
  { value: 'Africa/Nairobi', label: '(GMT+3:00) Nairobi' },
  { value: 'America/Argentina/Buenos_Aires', label: '(GMT-3:00) Buenos Aires' },
  { value: 'America/Bogota', label: '(GMT-5:00) Bogota' },
  { value: 'America/Chicago', label: '(GMT-5:00) Central Time (US & Canada)' },
  { value: 'America/Denver', label: '(GMT-6:00) Mountain Time (US & Canada)' },
  { value: 'America/Los_Angeles', label: '(GMT-7:00) Pacific Time (US & Canada)' },
  { value: 'America/Mexico_City', label: '(GMT-6:00) Mexico City' },
  { value: 'America/New_York', label: '(GMT-4:00) Eastern Time (US & Canada)' },
  { value: 'America/Phoenix', label: '(GMT-7:00) Phoenix' },
  { value: 'America/Sao_Paulo', label: '(GMT-3:00) Sao Paulo' },
  { value: 'America/Toronto', label: '(GMT-4:00) Toronto' },
  { value: 'America/Vancouver', label: '(GMT-7:00) Vancouver' },
  { value: 'Asia/Bangkok', label: '(GMT+7:00) Bangkok' },
  { value: 'Asia/Dubai', label: '(GMT+4:00) Dubai' },
  { value: 'Asia/Hong_Kong', label: '(GMT+8:00) Hong Kong' },
  { value: 'Asia/Jakarta', label: '(GMT+7:00) Jakarta' },
  { value: 'Asia/Karachi', label: '(GMT+5:00) Karachi' },
  { value: 'Asia/Kolkata', label: '(GMT+5:30) Kolkata' },
  { value: 'Asia/Kuala_Lumpur', label: '(GMT+8:00) Kuala Lumpur' },
  { value: 'Asia/Manila', label: '(GMT+8:00) Manila' },
  { value: 'Asia/Seoul', label: '(GMT+9:00) Seoul' },
  { value: 'Asia/Shanghai', label: '(GMT+8:00) Shanghai' },
  { value: 'Asia/Singapore', label: '(GMT+8:00) Singapore' },
  { value: 'Asia/Taipei', label: '(GMT+8:00) Taipei' },
  { value: 'Asia/Tokyo', label: '(GMT+9:00) Tokyo' },
  { value: 'Australia/Melbourne', label: '(GMT+10:00) Melbourne' },
  { value: 'Australia/Perth', label: '(GMT+8:00) Perth' },
  { value: 'Australia/Sydney', label: '(GMT+10:00) Sydney' },
  { value: 'Europe/Amsterdam', label: '(GMT+2:00) Amsterdam' },
  { value: 'Europe/Athens', label: '(GMT+3:00) Athens' },
  { value: 'Europe/Berlin', label: '(GMT+2:00) Berlin' },
  { value: 'Europe/Brussels', label: '(GMT+2:00) Brussels' },
  { value: 'Europe/Copenhagen', label: '(GMT+2:00) Copenhagen' },
  { value: 'Europe/Dublin', label: '(GMT+1:00) Dublin' },
  { value: 'Europe/Helsinki', label: '(GMT+3:00) Helsinki' },
  { value: 'Europe/Istanbul', label: '(GMT+3:00) Istanbul' },
  { value: 'Europe/Lisbon', label: '(GMT+1:00) Lisbon' },
  { value: 'Europe/London', label: '(GMT+1:00) London' },
  { value: 'Europe/Madrid', label: '(GMT+2:00) Madrid' },
  { value: 'Europe/Moscow', label: '(GMT+3:00) Moscow' },
  { value: 'Europe/Oslo', label: '(GMT+2:00) Oslo' },
  { value: 'Europe/Paris', label: '(GMT+2:00) Paris' },
  { value: 'Europe/Prague', label: '(GMT+2:00) Prague' },
  { value: 'Europe/Rome', label: '(GMT+2:00) Rome' },
  { value: 'Europe/Stockholm', label: '(GMT+2:00) Stockholm' },
  { value: 'Europe/Vienna', label: '(GMT+2:00) Vienna' },
  { value: 'Europe/Warsaw', label: '(GMT+2:00) Warsaw' },
  { value: 'Europe/Zurich', label: '(GMT+2:00) Zurich' },
  { value: 'Pacific/Auckland', label: '(GMT+12:00) Auckland' },
  { value: 'Pacific/Fiji', label: '(GMT+12:00) Fiji' },
  { value: 'Pacific/Honolulu', label: '(GMT-10:00) Honolulu' },
];
