
project_id = "htjvyzmuqsrjpesdurni"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

# Enable functions for our project
[functions]
[functions.add-to-calendar]
verify_jwt = true

[functions.generate-invoice-pdf]
verify_jwt = true

[functions.send-invoice-email]
verify_jwt = true

[functions.regenerate-invoice-html]
verify_jwt = true
