
project_id = "htjvyzmuqsrjpesdurni"

[functions.admin-get-users]
verify_jwt = false

[functions.admin-get-user-data]
verify_jwt = false

[functions.admin-update-user-status]
verify_jwt = true

[functions.create-subscription]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
